<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TMQ.BaseDomains\TMQ.BaseDomains.csproj" />
    <ProjectReference Include="..\TMQ.SystemCommands\TMQ.SystemCommands.csproj" />
    <ProjectReference Include="..\TMQ.SystemReadModels\TMQ.SystemReadModels.csproj" />
  </ItemGroup>

</Project>
