using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TMQ.Config
{
    public enum ConfigSettingEnum
    {
        AppName,
        AppVersion,
        HttpType,
        HttpPort,
        Https,
        LogEventLevel,
        LogToEsUrl,
        AuthenticationType,
        CookieAuthenName,
        CookieDomain,
        [Display(Name = "JwtTokens:Key")] JwtTokensKey,
        CORS,
        RedisPersistenceDbId,
        DataProtectionRedisKey,
        DataProtectionRedisDbId,
        IsDevEnvironment,
        RabbitMqExChange,
        RabbitMqRoutingRoot,
        RabbitMqExChangeNotify,
        RabbitMqExChangeTrigger,
        RabbitMqPrefetchCount,
        RabbitMqHost,
        VirtualHost,
        RabbitMqUserName,
        RabbitMqPassword,
        EventHandlerFilterQueues,
        RabbitMqRouting,
        RabbitMqQueues,
        RabbitMqExChangeTriggerListen,
        RabbitMqPoolSize,
        RabbitMqExChangeFERequest,
        RabbitMqRoutingFERequest,
        WorkerGroup,
        [Display(Name = "ConnectionStrings:DbConnectionString")]
        DbConnectionString,
        DbOldConnectionString,
        RedisPersistenceHostIps,
        RedisPassword,
        RedisHostIps,
        RedisCacheDbId,
        RedisPoolSize,
        StartWorker,
        EventDatabaseConnectionString,
        EventDatabaseName,
        EventCollectionName,
        RabbitMqExChangeNotifyListen,
        AdminUserIds,
        LoginExpiresTime,
        PathUrl,
        CdnDomain,
        CdnDomainKey,
        CdnDomainVideo,
        CdnDomainVideoKey,
        CacheEnable,
        EnableUpdateCacheFromWorker,
        IsLoadCache,
        EsUrl,
        AccountManagerUrl,
        SystemManagerUrl,
        ProductManagerUrl,
        LocationManagerUrl,
        NotificationManagerUrl,
        WarehouseManagerUrl,
        SurveyManagerUrl,
        TicketManagerUrl,
        NotificationProcessScheduleMessage,
        EmailSendRange,
        [Display(Name = "SmtpServer")] SmtpServer,
        [Display(Name = "SmtpPort")] SmtpPort,
        [Display(Name = "SmtpEnableSsl")] SmtpEnableSsl,
        [Display(Name = "SmtpAccount")] SmtpAccount,
        [Display(Name = "SmtpPassword")] SmtpPassword,
        [Display(Name = "AwsAccessKeyId")] AwsAccessKeyId,
        [Display(Name = "AwsSecretAccessKey")] AwsSecretAccessKey,
        [Display(Name = "AwsAccessKeyIdByMarketing")]
        AwsAccessKeyIdByMarketing,
        [Display(Name = "AwsSecretAccessKeyByMarketing")]
        AwsSecretAccessKeyByMarketing,
        [Display(Name = "NotificationDatabaseSettings:ConnectionString")]
        NotificationDatabaseConnectionString,
        [Display(Name = "NotificationDatabaseSettings:DatabaseName")]
        NotificationDatabaseName,
        [Display(Name = "NotificationDatabaseSettings:EmailCollectionName")]
        EmailCollectionName,
        [Display(Name = "NotificationDatabaseSettings:SMSCollectionName")]
        SMSCollectionName,
        [Display(Name = "NotificationDatabaseSettings:NotificationName")]
        NotificationName,
        [Display(Name = "NotificationDatabaseSettings:NotificationMessageName")]
        NotificationMessageName,
        [Display(Name = "NotificationDatabaseSettings:NotificationSettingName")]
        NotificationSettingName,
        [Display(Name = "NotificationDatabaseSettings:NotificationSettingManager")]
        NotificationSettingManager,
        [Display(Name = "NotificationDatabaseSettings:NotificationUserSetting")]
        NotificationUserSetting,
        [Display(Name = "NotificationDatabaseSettings:SyncEvent")]
        SyncEvent,
        SMSSendRange,
        [Display(Name = "SMSGateWayUrl")] SMSGateWayUrl,
        [Display(Name = "SMSGateWayAuthorizationKey")]
        SMSGateWayAuthorizationKey,
        [Display(Name = "SMSGateWayBrandName")]
        SMSGateWayBrandName,

        FileImageExtension,
        FileVideoExtension,
        FilePdfExtension,
        FileGifExtension,
        EnvironmentName,
        FileManagerUrl,
        [Display(Name = "GoogleRecaptchaDomain")]
        GoogleRecaptchaDomain,
        [Display(Name = "ChartDomain")] ChartDomain,
        [Display(Name = "StoreId")] StoreId,
        AdminWebsiteIdConfig,
        [Display(Name = "Domain")] Domain,
        [Display(Name = "CdnDomainPublicNotCopy")]
        CdnDomainPublicNotCopy,
        [Display(Name = "CdnDomainPublic")] CdnDomainPublic,
        [Display(Name = "CdnArticleCopy")] CdnArticleCopy,
        [Display(Name = "CdnArticleCopyPublic")]
        CdnArticleCopyPublic,
        [Display(Name = "CdnDomainEmbed")] CdnDomainEmbed,
        [Display(Name = "CdnDomainKeyEmbed")] CdnDomainKeyEmbed,

        [Display(Name = "ArticleDatabaseSettings:ConnectionString")]
        ArticleDatabaseConnectionString,
        [Display(Name = "ArticleDatabaseSettings:DatabaseName")]
        ArticleDatabaseName,
        [Display(Name = "ArticleDatabaseSettings:HistoryCollectionName")]
        ArticleCollectionName,
        LocalUploadTokenKey,
        [Display(Name = "CdnUrlLocalUpload")] CdnUrlLocalUpload,
        [Display(Name = "CdnUrlImageCopy")] CdnUrlImageCopy,
        ImageFolderPathPublish,
        OldDomainImages,
        DownloadImageProxy,
        ArticleEditLink,
        EmbedDomain,
        ImageThumpHashKey,
        DomainIframeResponsives,
        CdnDomainPublicValidToken,
        EnableLazyLoad,
        [Display(Name = "NoImageUrl")] NoImageUrl,
        ExtensionGrammarNotAllow,
        NewsManagerUrl,
        ActionKeyPrefix,
        ArticleDealerId,
        DealerId,
        UploadPublicPath,
        UploadPrivatePath,
        CarFamilyAttributeId,
        TermsArticleId,
        GoogleRecaptchaSecretKey,
        GoogleRecaptchaEnable,
        MaxImageFileSize,
        MaxVideoFileSize,
        MaxDocumentFileSize,
        MaxOtherFileSize,
        AllowedImageExtension,
        AllowedVideoExtension,
        AllowedAudioExtension,
        AllowedDocumentExtension,
        AllowedOtherExtension,
        AccountManagerAutomaticKeyGeneration,
        GoogleTokenInfoUrl,
        FacebookAppId,
        FacebookAppSecret,
        MicrosoftTokenInfoUrl,
        ZaloTokenInfoUrl,
        TrackingProduct,
        ProductDealerId,
        EnableLogByCurrentUser,
        ProvinceIdDefault,
        IsFileUploadCheckCaptcha,
        FileRootPath,
        FileRootPathPublic,
        FileRootPathPrivate,
        IsMasterData,
        DealerTMVId,
    }
}
