<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TMQ.AccountDomains\TMQ.AccountDomains.csproj" />
    <ProjectReference Include="..\TMQ.AccountReadModels\TMQ.AccountReadModels.csproj" />
    <ProjectReference Include="..\TMQ.BaseRepositories\TMQ.BaseRepositories.csproj" />
  </ItemGroup>

</Project>
